### ISSUE TITLE
Fix loading of scores, if score do not exits in the pdb 

### ISSUE THREAD

**Issue by ajasja** [ajasja/rosetta_pymol_utils#2]
```
PyMOL>delete *
PyMOL>lrp $PATH/model.pdb
Traceback (most recent call last):
  File "pymol_utils.py", line 658, in load_rosetta_pdb
    import_scores(pdb, object_name=object)
  File "pymol_utils.py", line 501, in import_scores_from_pdb
    \n cvs_header:{reader.fieldnames}"
AssertionError: Fields {'fa_sol', 'fa_atr', 'fa_elec', 'fa_rep', 'fa_dun_rot'} are not in the PDB energy table.             
 fields    :['total', 'fa_rep', 'fa_atr', 'fa_sol', 'fa_elec', 'fa_dun_rot']             
 cvs_header:['label', 'vdw', 'hbond_sr_bb', 'hbond_lr_bb', 'pair', 'rama', 'env', 'cbeta', 'rg', 'chainbreak', 'total']
```

**Comment by ajasja** [comment]
Also allow passing of fields through `lrp`
